// #Random Values for display
export const statsData = [
  {
    id: "total-users",
    title: "Total Users",
    value: "12,456",
    change: "+18.6%",
    trend: "up",
    icon: "users",
    description: "vs last week",
  },
  {
    id: "total-orders",
    title: "Total Orders",
    value: "8,942",
    change: "+12.4%",
    trend: "up",
    icon: "orders",
    description: "vs last week",
  },
  {
    id: "total-revenue",
    title: "Total Revenue",
    value: "₹ 1,24,560",
    change: "+24.8%",
    trend: "up",
    icon: "revenue",
    description: "vs last week",
  },
  {
    id: "pending-orders",
    title: "Pending Orders",
    value: "1,248",
    change: "+8.2%",
    trend: "up",
    icon: "tasks",
    description: "vs last week",
  },
];

export const recentActivityData = [
  {
    id: 1,
    user: "John Doe",
    action: "iPhone 15 Pro",
    module: "Billing",
    status: "completed",
    timestamp: "May 26, 2025",
    avatar: "JD",
    amount: "₹ 1,29,999",
  },
  {
    id: 2,
    user: "Jane Smith",
    action: "MacBook Air",
    module: "Inventory",
    status: "pending",
    timestamp: "May 26, 2025",
    avatar: "JS",
    amount: "₹ 89,999",
  },
  {
    id: 3,
    user: "Robert Brown",
    action: "Wireless Earbuds",
    module: "HR",
    status: "shipped",
    timestamp: "May 25, 2025",
    avatar: "RB",
    amount: "₹ 4,999",
  },
  {
    id: 4,
    user: "Emily Davis",
    action: "Smart Watch",
    module: "Analytics",
    status: "failed",
    timestamp: "May 24, 2025",
    avatar: "ED",
    amount: "₹ 12,499",
  },
  {
    id: 5,
    user: "Rahul Sharma",
    action: "Wireless Headphones",
    module: "Procurement",
    status: "completed",
    timestamp: "May 24, 2025",
    avatar: "RS",
    amount: "₹ 7,499",
  },
];

export const notificationsData = [
  {
    id: 1,
    type: "success",
    title: "New order received",
    message: "#ORD1256",
    time: "2 min ago",
    read: false,
  },
  {
    id: 2,
    type: "info",
    title: "Server backup completed",
    message: "System",
    time: "15 min ago",
    read: false,
  },
  {
    id: 3,
    type: "info",
    title: "New message received",
    message: "From Sarah",
    time: "25 min ago",
    read: false,
  },
  {
    id: 4,
    type: "success",
    title: "Payment of ₹3,450",
    message: "Completed",
    time: "1 hr ago",
    read: true,
  },
  {
    id: 5,
    type: "warning",
    title: "License Expiring",
    message: "Software license expires in 7 days",
    time: "2 hr ago",
    read: true,
  },
];

export const navLinks = [
  { id: "dashboard", label: "Dashboard", icon: "dashboard", href: "/" },
  { id: "users", label: "Users", icon: "users", href: "/users" },
  { id: "products", label: "Products", icon: "inventory", href: "/products" },
  { id: "orders", label: "Orders", icon: "orders", href: "/orders" },
  { id: "customers", label: "Customers", icon: "users", href: "/customers" },
  { id: "analytics", label: "Analytics", icon: "analytics", href: "/analytics" },
  { id: "reports", label: "Reports", icon: "reports", href: "/reports" },
  { id: "settings", label: "Settings", icon: "settings", href: "/settings" },
  { id: "support", label: "Support", icon: "billing", href: "/support" },
];

export const currentUser = {
  name: "Admin User",
  role: "Super Admin",
  email: "admin@smartvyapar.com",
  avatar: "/logo.png",
  department: "Management",
};
